// <auto-generated />
using Gama.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gama.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241215012346_CustomerInclusion")]
    partial class CustomerInclusion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Gama.API.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerAddress = "123 Main St",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            CustomerAddress = "456 Elm St",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 3,
                            CustomerAddress = "789 Oak St",
                            Name = "Bob Johnson"
                        },
                        new
                        {
                            Id = 4,
                            CustomerAddress = "101 Maple St",
                            Name = "Alice Brown"
                        },
                        new
                        {
                            Id = 5,
                            CustomerAddress = "202 Pine St",
                            Name = "Charlie Davis"
                        },
                        new
                        {
                            Id = 6,
                            CustomerAddress = "303 Cedar St",
                            Name = "Emily Evans"
                        },
                        new
                        {
                            Id = 7,
                            CustomerAddress = "404 Birch St",
                            Name = "Frank Harris"
                        },
                        new
                        {
                            Id = 8,
                            CustomerAddress = "505 Walnut St",
                            Name = "Grace Kelly"
                        },
                        new
                        {
                            Id = 9,
                            CustomerAddress = "606 Chestnut St",
                            Name = "Hank Lee"
                        },
                        new
                        {
                            Id = 10,
                            CustomerAddress = "707 Spruce St",
                            Name = "Isabel Moore"
                        },
                        new
                        {
                            Id = 11,
                            CustomerAddress = "808 Fir St",
                            Name = "Jack Nelson"
                        },
                        new
                        {
                            Id = 12,
                            CustomerAddress = "909 Redwood St",
                            Name = "Kathy Owens"
                        },
                        new
                        {
                            Id = 13,
                            CustomerAddress = "100 Ash St",
                            Name = "Leo Parker"
                        },
                        new
                        {
                            Id = 14,
                            CustomerAddress = "111 Cypress St",
                            Name = "Mona Queen"
                        },
                        new
                        {
                            Id = 15,
                            CustomerAddress = "222 Dogwood St",
                            Name = "Nancy Robinson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
